apiVersion: v1
kind: Pod
metadata:
  name: babyapp-pod
spec:
  containers:
  - name: babyapp-container
    image: ghcr.io/cosmo-tech/backend-tf-state-to-vault:latest
    command: ["/bin/bash", "-c", "python main.py config write -use-azure"]
    env:
    - name: VAULT_ADDR
      value: "$VAULT_ADDR"
    - name: VAULT_TOKEN
      value: "$VAULT_TOKEN"
    - name: TENANT_ID
      value: "$TENANT_ID"
    - name: ORGANIZATION_NAME
      value: "$ORGANIZATION_NAME"
    - name: CLUSTER_NAME
      value: "$CLUSTER_NAME"
    - name: STORAGE_ACCOUNT_NAME
      value: "$STORAGE_ACCOUNT_NAME"
    - name: STORAGE_ACCOUNT_KEY
      value: "$STORAGE_ACCOUNT_KEY"
    - name: STORAGE_CONTAINER
      value: "$STORAGE_CONTAINER"
    - name: TFSTATE_BLOB_NAME
      value: "$TFSTATE_BLOB_NAME"
    - name: PLATFORM_NAME
      value: "$PLATFORM_NAME"
